### ISSUE TITLE
338 carrier type

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#148]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/3XX.csv

**Comment by CECSpecialistI** [comment]
Decided during 2023-05-03 meeting we should examine values and re-evaluate mapping output to use RDA values whenever possible, and create map/alignment from RDA VES to id.loc VES and send to RSC to see if they will add to RDA Registry. @szapoun will post National Library of Greece alignments, @GordonDunsire will look at it

**Comment by szapoun** [comment]
NLG mapping for 338
[338.xlsx](https://github.com/uwlib-cams/MARC2RDA/files/11403621/338.xlsx)

**Comment by GordonDunsire** [comment]
I have checked the NLG alignment and don't see any errors.

For the purposes of an RDA to MARC 21 mapping, RDA prefers to use SKOS to relate RDA concepts, which are already expressed in SKOS, to external concepts.

The LC concepts are also expressed in SKOS, albeit alongside a MADS representation.

In all cases, I think the correct alignment and mapping is SKOS "close match".

The LC vocabulary and concepts appear to be a near copy of the RDA vocabulary, although it has additional, non-RDA concepts.

[RDACT2M21NT.txt](https://github.com/uwlib-cams/MARC2RDA/files/11430930/RDACT2M21NT.txt)

RDACT2M21NT is an n-triples version of the map (in text format for GitHub purposes). The NT format is suitable for submitting the map to the RSC Technical Working Group for approval and publication in the RDA Registry.

Note: skos:closeMatch is effectively a symmetric property, so the map can be flipped and used to reverse-engineer M21 data that uses the M21 vocabulary.

**Comment by cspayne** [comment]
Hi Matt,

You're correct in that the 338 mapping table indicates we're transforming all $0s and $1s that we can. However, the [code](https://github.com/uwlib-cams/MARC2RDA/blob/4f852a19a097e1c1bd7d5a0556a92abc1651deb3/Working%20Documents/transformationCode/m2r-3xx-named.xsl#L1142) still has a condition in F338-iri that only transforms $0s if there aren't any $1s. If @tmqdeborah agrees that we are transforming all $0s and $1s possible, then that if condition should be removed! Hope that clears things up, but let me know if you have any other questions. 

Best,
Cypress

**Comment by cspayne** [comment]
Coming back to the multiple $0s breakpoint, I think something like this should work: 
```xml
       <xsl:variable name="sub0Test">
            <xsl:value-of select="if (some $sub0 in marc:subfield[@code = '0'] satisfies 
                contains($sub0, 'http')) then 'Yes' else 'No'"/>
       </xsl:variable>

       <xsl:if test="not(marc:subfield[@code = '1']) and $sub0Test = 'No'">
```
It will also need to be fixed in all the other 3XX-string templates, it's an error that we just hadn't caught yet. Maybe we should start a separate issue for this?

**Comment by tmqdeborah** [comment]
What about multiple $1?

**Comment by tmqdeborah** [comment]
@MHill-BL, trying again to actually attach the correct file of my test records.

[338.Test.fields.for.Attributes.coding.txt](https://github.com/user-attachments/files/20796962/338.Test.fields.for.Attributes.coding.txt)

In case sending it this way doesn't work, I will also send it as an email attachment. 

Could you please run this through your test_input/test_out procedure.  If you can't use it in this format, I'll try making real MARCXML records for the examples.

If you are able to run the file, I will see how it loads to RIMMF, since I, too, struggle to read rdf :-}

**Comment by MHill-BL** [comment]
Hi Deborah, I added all of these examples into the input at: [link](https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/transformationCode/test_input/3xx/338Test.xml)

**Comment by MHill-BL** [comment]
Hi Deborah, i have updated the 338 spreadsheet with links within the code. Thanks

**Comment by tmqdeborah** [comment]
Matt, thanks for the links, I find them very useful.

I reviewed the result file yesterday and it is looking pretty good, but I found a few issues. 

Please change the following:
  - IF $3 is present, THEN map the value of **one** of $a or $b or $1 or $0 as the equivalent value from [**RDA Term**] to 'note on manifestation (datatype P30137) with prefix "Carrier type: ", and append "applies to" AND "[value of $3, with first word capitalized]", e.g., "Carrier type: volume applies to Lyrics"
      - current coding is producing this "Carrier type http://id.loc.gov/vocabulary/carriers/sd applies to the manifestation's test3"; should be "Carrier type: audio disc applies to Test3"
https://github.com/uwlib-cams/MARC2RDA/blob/e0106893c8ce4d7359456b68382a9dbeff138d36/Working%20Documents/transformationCode/m2r-3xx-named.xsl#L1162
    
  - If $0|$1 is an id.loc.gov URI that maps to [RDACarrierType] in the table, use the RDACarrierType, not the id.loc.gov URI
    -  A number of times within the code

Would it be possible for you to run only my examples through the transform, so that I can better see what happens to them?

A revised list of examples is attached, with corrections to the last 4 fields:

[338.Test.fields.for.Attributes.coding.txt](https://github.com/user-attachments/files/20837361/338.Test.fields.for.Attributes.coding.txt)

Note that I have also clarified the INSTRUCTIONS FOR APPLYING TO 'MODES' (which summarize the IF/THEN statements under BASE INSTRUCTIONS with amendments for applying those statements for APs and IRIs)

**Comment by tmqdeborah** [comment]
There has been much community discussion about the appropriate RDA carrier type value to use for "audio media devices" and "video media devices" aka standalone devices, such as Playaway, Go Reader, etc. See, e.g.:
- [OLAC](https://cornerstone.lib.mnsu.edu/olac-publications/24/)
- [Best Practices for Cataloging Digital Media Storage Devices](https://cornerstone.lib.mnsu.edu/olac-publications/30/)

I recommend that when none of the [RDA carrier type ](https://www.rdaregistry.info/termList/RDACarrierType/) values apply to a bibliographic resource, we should either map:
- carrier type 'object'
- no carrier type (this might be a better alternative for mapping, given the variety of terms being used in existing records)

This policy would also apply to kits since we are describing the kit and its contents, i.e., the kit is an object (or no carrier type) and the carrier types for the contents, if we choose to list them, can be recorded as appropriate.

@GordonDunsire can you please give your opinion on this?

**Comment by CECSpecialistI** [comment]
@tmqdeborah @cspayne where are we on the 338? Is this a code re-check, almost done/needs decision, or done?

**Comment by tmqdeborah** [comment]
The 338 table is done and working well. 

@cspayne is working on converting values from a variety of MARC fields to 336, 337, and 338 values for all the many records that do not have those fields already present.
