### ISSUE TITLE
340 physical medium

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#149]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/3XX.csv

**Comment by gerontakos** [comment]
340 $n is the "font size" subfield. In this subfield catalogers enter phrases like "giant print," point size measurements like "36 point," or some combination of those: "giant print (36 point)."
In RDA there are two elements for font size:
(1) hasFontSize
(2) hasFontPointSize
The best solution seems to just make all 340$n values the values of rdam:hasFontSize.
Will this result in errors or bad RDA?

**Comment by gerontakos** [comment]
A question has arisen while working on MARC 340: if a particular mapping is not necessarily lossy but only potentially lossy, should it be marke status = loss or somethng else, like status = first pass?
Specific to the 340: all 340 fields with ( ($0 | $1) AND ($* > 1) ) might require all 340$0 and 340$1 rows in the spreadsheet to have status = "loss." (Actually it's not all subfields, i.e. $*, but most.) This is because we don't know which subfield should be paired with the given $0 or $1 value. It is not a necessary loss, just potential loss.

**Comment by gerontakos** [comment]
The subfields $b $f $h and $i need a close review. $h for example is "location within medium" -- the location, that is, of the material entered in one of the other subfields. The note created for $h, for example, is very poor right now and would be improved by designing it in combination with a single subfield. In that case, as with $0 and $1, if there are multiple subfields, the subfield will require some generic note. So @gerontakos do review these fields again.

**Comment by GordonDunsire** [comment]
Mapping 340 $n to rdam:P30199 "has font size" is not an error. rdam:P30306 "has font point size" was introduced to allow numeric values to be computed for, say, limiting searches by end-users with visual requirements. The MARC 21 manual does not indicate any regular syntax for adding the point size, so it would be very difficult to parse it out; the value is fine if it is left as part of the more general statement on font size.

**Comment by gerontakos** [comment]
NOTE FOR THE REVIEWER OF FIELD 340 REGARDING 340$b. 340$b without 340$a is not expected. We are not giving the dimensions of the manifestation but, rather, whatever is specified in 340$a. Current mapping clarifies this by appending the value of 340$a to the value of 340$b as a parenthetical qualifier. The official RDA/MARC alignment recommends an alignment with 340$b and the properties rdam:hasDimensionsOfCartographicImage and rdam:hasDimensionsOfStillImage but the value of 340$a should not be either the content type cartographic image or the content type still image, so the current mapping deletes those properties. Finally, it is possible that the presence of $0, $1, or $3 without $a allows a mapping of $b; however, the current mapping recommends "do not map" if there is no $a.

**Comment by pan-zhuo** [comment]
Seems that "base material", "applied material", and "mount" have been soft deprecated in favor of "material". http://rdaregistry.info/Elements/m/P30304

**Comment by cspayne** [comment]
@pennylenger 
Hi Penny! For $b, if there is no $a do we still map it? I'm seeing records where $a is not present with $b in this field.

**Comment by cspayne** [comment]
@pennylenger 
Also, should we map $3 for subfields b, f, h, and i? I'm not seeing them in the mapping sheet. Thank you.

**Comment by cspayne** [comment]
> @pennylenger Hi Penny! For $b, if there is no $a do we still map it? I'm seeing records where $a is not present with $b in this field.

I now see Theo's recommendation on $b is to only map when $a is present.

**Comment by pennylenger** [comment]
Hi Cypress,

Thank you for asking.  I have added $3 to $b, f, h, and i. I hope it is
clear, if not, please help revise them. Thank you !
I find *$f - Reduction ratio value is missing in the sheet now.  Should I
add it back? There is a obsolete one **$f - Production rate/ratio [RENAMED,
2022] [REDEFINED, 2022]*

*Penny*

**Comment by tmqdeborah** [comment]
I do not agree with Theo's recommendation.

There are many records in the LC file that I have, with:
- $a $b, etc.
  340    $a vinyl $b 12 in. $2 rda
  340    $a plastic $a metal $b 4 3/4 in. $f 1.4 m/s $j mass-produced
- $a only
  340    $a vinyl $2 rdamat
- $b only
   340    $b 12 in.
- $a and separate $b: 
  340    $a vinyl $2 rdamat
  340    $b 12 in.

It appears that the subfields (or at least the $b) can appear alone or in combination with other subfields. 

My advice is to map the values of the subfields whether they are given alone or in combination with other subfields.

Note that the data values in some these subfields will often also be provided in 300$b or $c

**Comment by cspayne** [comment]
> Hi Cypress, Thank you for asking. I have added $3 to $b, f, h, and i. I hope it is clear, if not, please help revise them. Thank you ! I find *$f - Reduction ratio value is missing in the sheet now. Should I add it back? There is a obsolete one **$f - Production rate/ratio [RENAMED, 2022] [REDEFINED, 2022]* *Penny*

Apologies, I had marked that row 'delete' because it did not map to any property, but I have moved it back to 'reviewed' although it is still a blank row. Was this just not mapped yet?

**Comment by pennylenger** [comment]
> > Hi Cypress, Thank you for asking. I have added $3 to $b, f, h, and i. I hope it is clear, if not, please help revise them. Thank you ! I find *$f - Reduction ratio value is missing in the sheet now. Should I add it back? There is a obsolete one *_$f - Production rate/ratio [RENAMED, 2022] [REDEFINED, 2022]_ _Penny_
> 
> Apologies, I had marked that row 'delete' because it did not map to any property, but I have moved it back to 'reviewed' although it is still a blank row. Was this just not mapped yet?

No worries. I have added the mapping. The value is supposed to be structured, so I didn't write the transformation note. But I now think it should be unstructured because I don't know how it can be recorded in structured description. And I added $3 for this.

**Comment by cspayne** [comment]
> > > Hi Cypress, Thank you for asking. I have added $3 to $b, f, h, and i. I hope it is clear, if not, please help revise them. Thank you ! I find *$f - Reduction ratio value is missing in the sheet now. Should I add it back? There is a obsolete one *_$f - Production rate/ratio [RENAMED, 2022] [REDEFINED, 2022]_ _Penny_
> > 
> > 
> > Apologies, I had marked that row 'delete' because it did not map to any property, but I have moved it back to 'reviewed' although it is still a blank row. Was this just not mapped yet?
> 
> No worries. I have added the mapping. The value is supposed to be structured, so I didn't write the transformation note. But I now think it should be unstructured because I don't know how it can be recorded in structured description. And I added $3 for this.

Hi Penny! Should the obsolete mapping be deleted now that we've updated the mapping for $f?

**Comment by pennylenger** [comment]
> > > > Hi Cypress, Thank you for asking. I have added $3 to $b, f, h, and i. I hope it is clear, if not, please help revise them. Thank you ! I find *$f - Reduction ratio value is missing in the sheet now. Should I add it back? There is a obsolete one *_$f - Production rate/ratio [RENAMED, 2022] [REDEFINED, 2022]_ _Penny_
> > > 
> > > 
> > > Apologies, I had marked that row 'delete' because it did not map to any property, but I have moved it back to 'reviewed' although it is still a blank row. Was this just not mapped yet?
> > 
> > 
> > No worries. I have added the mapping. The value is supposed to be structured, so I didn't write the transformation note. But I now think it should be unstructured because I don't know how it can be recorded in structured description. And I added $3 for this.
> 
> Hi Penny! Should the obsolete mapping be deleted now that we've updated the mapping for $f?

Hi Cypress, I think the obsolete subfield should still be mapped and transformed because some old records may use this subfield and we need to keep the data in that field.

**Comment by pennylenger** [comment]
> > > > > Hi Cypress, Thank you for asking. I have added $3 to $b, f, h, and i. I hope it is clear, if not, please help revise them. Thank you ! I find *$f - Reduction ratio value is missing in the sheet now. Should I add it back? There is a obsolete one *_$f - Production rate/ratio [RENAMED, 2022] [REDEFINED, 2022]_ _Penny_
> > > > 
> > > > 
> > > > Apologies, I had marked that row 'delete' because it did not map to any property, but I have moved it back to 'reviewed' although it is still a blank row. Was this just not mapped yet?
> > > 
> > > 
> > > No worries. I have added the mapping. The value is supposed to be structured, so I didn't write the transformation note. But I now think it should be unstructured because I don't know how it can be recorded in structured description. And I added $3 for this.
> > 
> > 
> > Hi Penny! Should the obsolete mapping be deleted now that we've updated the mapping for $f?
> 
> Hi Cypress, I think the obsolete subfield should still be mapped and transformed because some old records may use this subfield and we need to keep the data in that field.

I realize it is difficult to differentiate an old $f and a new $f. They are both $f.

**Comment by cspayne** [comment]
Since there will be values for both old $f and new $f, would it be best to map to 'has note on manifestation'?

**Comment by pennylenger** [comment]
I agree. I have updated the mapping.

**Comment by cspayne** [comment]
@AdamSchiff @CECSpecialistI @tmqdeborah 
Will $1s (and $0s) only be used when there is one other subfield (not including $2 and $3)? 
i.e. will a $1 be used if there are multiple subfield $a's or multiple different subfields such as $a and $b? If so, there is no way to know which one relates to the $1 and what property to use. 

I know that it is preferred to use a separate field for each unique term, but I don't know if we can assume that every record we process will follow that. In the case that multiple terms appear in the same field, do we need to account for the possible presence of a $0 or $1 as well?

**Comment by AdamSchiff** [comment]
If a subfield is repeatable, we can expect to find records with that.  We can also expect to find some repeated $0s or $1s.   The $0/$1 should not be repeated if there are multiple controlled subfields since it's impossible to know what goes with what.  That's true of the same subfield or different ones.  But I can't guarantee that all records will follow this best practice.

When the Authority Toolkit adds URIs, if a field has multiple subfields it breaks them up into separate fields, each with just one vocabulary subfield and then it adds the $0 and/or $1 for that term.

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
Box 352900
Seattle, WA 98195-2900
aschiff @ uw.edu
________________________________

**Comment by cspayne** [comment]
It seems to me that we can only use a $0 or $1 value when there is only one other subfield (not including $2, $3, $6 or $8). In this case we know what property to use because there is only one subfield that the IRI provided in a $0 or $1 could go with. 

When there are multiple subfields, we can't know what property to map the $0 or $1 to since we do not know which subfield the $0 or $1 goes with. In this case, I think we have to discard the $0 or $1 value and process each subfield instead.

**Comment by lake44me** [comment]
If we're talking about 340 here, maybe...  this gets too complicated.  I suspect $0 or $1 would be used for same purpose as $2 - to link to  the value vocabulary used.  One of the examples in the MARC document:

340  ##$3teacher edition$lcase binding$2rdatb  

that's gotta be  http://www.rdaregistry.info/termList/#RDATypeOfBinding, in a $0 or $1 it would only be applicable to $l Binding so if there were other subfields you'd know which it pertained to.  

But for this pass through the mapping, I think it'd be too much to try to build something like that into the logic.  Maybe it could be noted in our documentation and thought about for a future phase if it turns out to be a problem and we're dropping too many $0/$1's .

**Comment by AdamSchiff** [comment]
Yes, I agree.  The field should be split up into multiple fields, each with a $0 or $1 when there are multiple subfields with controlled values, whether it is the same subfield repeated, or diffferent subfields.

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by cspayne** [comment]
For $0s and $1s, I have this coded so that they are only used if there is only one subfield containing a vocabulary term (a subfield that is not subfields b, f, h, i, 2, 3, 6, 8). Other subfields that may contain vocabulary terms make it impossible to know which subfield the 0 or 1 is related to and thus which property to use, so the 0 or 1 should be ignored.
