### ISSUE TITLE
518 date/time and place of an event note

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#196]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by cspayne** [comment]
@CECSpecialistI 
Ying-Hsiang, Penny, and I are looking at the mapping for $0 for this field. It is defined as a "control number of the record for a controlled place term in subfield $p" and is currently mapped as "related nomen of nomen" for the nomen in $p. 
Is a control number of a record a nomen? Can we map it this way or should we not map it at all?

**Comment by CECSpecialistI** [comment]
> @CECSpecialistI Ying-Hsiang, Penny, and I are looking at the mapping for $0 for this field. It is defined as a "control number of the record for a controlled place term in subfield $p" and is currently mapped as "related nomen of nomen" for the nomen in $p. Is a control number of a record a nomen? Can we map it this way or should we not map it at all?

Bleh. This is phrased so strangely in the MARC standard. $0 is an identifer for the value in $p. So...an identifier for the nomen for the place. Can we process it as we do with other $0's but have it apply to just the $p value?

**Comment by cspayne** [comment]
I don't think we've dealt with $0s in 5XX fields or made a broader decision on how to handle identifiers like these in $0s...have we?

**Comment by pennylenger** [comment]
@CECSpecialistI Hi Crystal, can we also talk about $0s in 518 or 5XX fields in tomorrow's meeting?

**Comment by GordonDunsire** [comment]
The MARC 21 manual says for field 518: 'Field 033 (Date/Time and Place of an Event) contains the same information in coded form'.

The spreadsheet for field 033 shows that this information is not mapped to 'has note on manifestation', but is associated with a work or expression. The problem is: what work or expression? We cannot transform 518 to 'has note on manifestation'.

We can transform subfield $0 using a similar approach as for field 651, but the relationship element will be 'has related place of manifestation'. This is a bit of a stretch.

A further complication is shown in one of the examples for subfield $o (the letter, not the number) which gives a value of 'Rome and Venice' for subfield $p; that is, we cannot reliable transform subfield $p itself as a place.

**Comment by CECSpecialistI** [comment]
Check $0's semantics, don't base mappability on value in $p.

**Comment by CECSpecialistI** [comment]
@GordonDunsire I'm not sure why we can't map this field to "has note on manifestation" with boilerplate added like "Note on date/time and place of an event: ". At this point I'm not sure what else we can do without just throwing it out and hoping for phase II. Are you suggesting an alternative?

**Comment by pennylenger** [comment]
We are currently evaluating the type of entity that the authority in the $0 from different sources references based on Adam's table, in order to determine the best approach for addressing $0 in general. If the source entity type is equivalent to or a subtype of rda:Place, we can reliably transform subfield $p as a place. However, this might be too complex for field 518.  And  date and time typically map to the work and expression levels, since our transformation is based on a single work and expression, this approach might not be entirely suitable either.

**Comment by cspayne** [comment]
Following @CECSpecialistI and @GordonDunsire's suggestion and mapping to has note on manifestation for now. This may be revisited at a later date.

**Comment by hinxcode** [comment]
@cspayne I've updated the [code](https://github.com/uwlib-cams/MARC2RDA/commit/36b5487b533574309d985b27de03869663cedd99?diff=unified&w=0) according to the adjusted logic we discussed. Please feel free to comment or let me know if you have any further feedback.

**Comment by CECSpecialistI** [comment]
> [@cspayne](https://github.com/cspayne) - I was looking at this as part of the Mapping Spreadsheet Clean-up. There are some rows with ?, but it looks like they're actually accounted for in the code and could be changed to done. Would you mind confirming there's nothing more needed? If so, I can change them to done and do the clean-up. Thanks!

Mapping spreadsheet is cleaned up.
