### ISSUE TITLE
520 summary, etc.

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#197]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by pennylenger** [comment]
@lake44me @GordonDunsire @AdamSchiff @tmqdeborah   520 - Summary is mapped to has summarization of content. I am wondering why not has summary. Is summary at expression level, not work? And can the summary be for part of the described materials if $3 is present?  (not related, is table of contents at expression level?) Thank you!

**Comment by AdamSchiff** [comment]
Penny,

"has summary" is an element that has domain work and range work.  This is a relationship between two works.  This element would never be recorded in a 520 field.  It would be used in a 7XX field:

245   Work 1
7XX  $w r $i Summary: $a Work 2

520 is used to give a summary in a paragraph of the work being described.

"has summarization of content" doesn't point to another work, it has domain expression but no range at all because there is no other entity being pointed to, just a textual summary.

Does this explain it?

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by pennylenger** [comment]
Yes, thank you! Adam

**Comment by dchen077** [comment]
@pennylenger Hi Penny, for the transformation notes, I was wondering if you could help clarify whether the presence or absence of quotation marks is intentional. (i.e. Applies to for # and 8 doesn't have "" but the rest of the indicators do). Thanks!

**Comment by pennylenger** [comment]
Hi Doreen, sorry for the confusion. Applies to for # and 8 should also have quotation like "value of $3".
