### ISSUE TITLE
521 target audience note

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#198]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by lake44me** [comment]
I am selecting "has intended audience of expression" as the property for mapping the string in $a .  Reasoning is to assume target audience will not vary between expression and manifestation since content is same, so choose this over "has intended audience of manifestation".

**Comment by lake44me** [comment]
Issue related to first indicator:  definition "Display constant".  The effect of this is to append the constant in front of the contents of $a in a display interface.  For end users viewing descriptions, the bare content of $a (example, if indicator 1 i= 0, the constant is "Reading grade level", and the content of a $a = "3.1")  wouldn't make sense without the constant being visible before the $a text   Without a more granular RDA property for, say, "intended audience reading grade level of expression", or a way to use an RDA property that would modify the statement containing $a without reifying the statement (is there?),  the alternative would be to map (in a transformation) the textual value of indicator 1 (if there is one), add a colon, and concatenate this to the beginning of the content of $a as the object of the "has intended audience of expression" triple.  

An obstacle to doing this might be that $a is repeatable (drat!).  However, all subfield $a's in a tag would share the same indicator 1 value, so the "display constant" could be appended in front of each one as it was mapped to RDA without ambiguity.

**Comment by lake44me** [comment]
The other challenge for 521 is what to do about $b,  Source, defined as "Name or abbreviation of the agency or entity that determined the target audience of the item. ".   Examples in MARC21 include "LENOCA" (haven't been able to find out what this is an acronym for),  "Follett Library Book Co." which has groupings of grade levels, and "Center for Disabilities" (whose?)...  I haven't looked but I suspect there is no MARC code or term list for $b values.

I think in order to associate the source with the content of $a, we would have to reify the statement in subfield a, and then apply the Data Provenance aspect of RDA https://access.rdatoolkit.org/Guidance/Index?externalId=en-US_ala-cfa18e03-17f2-378a-874c-86515bf7e0ac .  The section that seems most applicable, to me at first reading, is 
CONDITION

A potential source of metadata is not a manifestation that is being described.

A potential source of metadata does not provide additional content for a metadata work.
OPTION

Record the source of metadata as a Work: [note on metadata work](https://access.rdatoolkit.org/Content/Index?externalId=en-US_ala-3decef2d-b430-3210-9e6d-c66fbe8e514d)[](https://access.rdatoolkit.org/Guidance/Index?externalId=en-US_ala-cfa18e03-17f2-378a-874c-86515bf7e0ac#) of the metadata work and indicate that additional information is not found in the source.

**Comment by lake44me** [comment]
One more thought - MARC21 https://www.loc.gov/marc/bibliographic/bd521.html states a relationship with an 008 code  "Information about the target audience and/or intellectual level may also be recorded in coded form in field 008/22 (Target audience) for some types of material."  There is a controlled value list for this I think:  https://id.loc.gov/vocabulary/maudience.html .

**Comment by CECSpecialistI** [comment]
I wonder whether an unconstrained property might be best here too? I'm thinking of large text or braille manifestations of the same expression being intended for different audiences? Would there ever be notes for that? Are those at the manifestation level?

**Comment by lake44me** [comment]
Not sure I understand your answer here.  Unconstrained properties aren't supposed to be associated with RDA Entities, and we would have to have a URI for the subject of them, right?  

I'm just saying, for a subfield indicating the source of a term or code in another subfield, either that gets appended to the string, or that string has to somehow become the subject of a predicate of some kind, with the source as an object.  Or the triple becomes the subject (which means, it's reified, one way or another - meaning, either as a blank node which then lists the subject, predicate and object, or by creating a URI for the triple and then giving the subject, predicate and object.

Some years ago I came across [this blog post](https://blogs.library.duke.edu/dcthree/2013/07/27/the-trouble-with-triples/) from Hugh Cayless at Duke who was working in the digital humanities area, and I think his points still hold, and I wonder if we would all be better of if his suggestion to apply an identifier (which could be made a URI) to every triple, became general practice..  ?

**Comment by pan-zhuo** [comment]
> The other challenge for 521 is what to do about $b, Source, defined as "Name or abbreviation of the agency or entity that determined the target audience of the item. ". Examples in MARC21 include "LENOCA" (haven't been able to find out what this is an acronym for), "Follett Library Book Co." which has groupings of grade levels, and "Center for Disabilities" (whose?)... I haven't looked but I suspect there is no MARC code or term list for $b values.
> 
> I think in order to associate the source with the content of $a, we would have to reify the statement built from $a, and then apply the Data Provenance aspect of RDA https://access.rdatoolkit.org/Guidance/Index?externalId=en-US_ala-cfa18e03-17f2-378a-874c-86515bf7e0ac . The section that seems most applicable, to me at first reading, is CONDITION
> 
> A potential source of metadata is not a manifestation that is being described.
> 
> A potential source of metadata does not provide additional content for a metadata work. OPTION
> 
> Record the source of metadata as a Work: [note on metadata work](https://access.rdatoolkit.org/Content/Index?externalId=en-US_ala-3decef2d-b430-3210-9e6d-c66fbe8e514d) of the metadata work and indicate that additional information is not found in the source.
> 
> Not entirely comfortable with this. I suspect a lot of this metadata, especially reading level, is taken from information on the cover/jacket/initial pages of books and the scheme is transcribed from what's found there.
> 
> Fortunately, $b is not repeatable, so only one source applies to multiple $a subfields if they are present .

I think this condition is applicable only when the source does not contain the information needed, like the Authority tag 675. When information is available and taken from a source that is not the book being described, the condition above this one applies (50.43.53.04):
CONDITION
A source of metadata is not a manifestation that is being described.

OPTION
Record the source of information as a [Work: source consulted](http://www.rdaregistry.info/Elements/w/#P10406) of the metadata work.

If the information is taken from within the book being described, apply the option at (18.62.79.47):
CONDITION
The source of a metadata work is a manifestation that is being described.

OPTION
Record the source of information as a [Work: recording source](http://www.rdaregistry.info/Elements/w/#P10404).

The problem with $b for me is that it records the name of an agency. It tells nothing about where that name is taken from, either the book in hand or a VES. So I'm leaning toward [Work: related agent of work](http://www.rdaregistry.info/Elements/w/#P10311) and its subtypes, or [Work: note on metadata work](http://www.rdaregistry.info/Elements/w/#P10402) stating something like 'assigned by [value of $b].'

**Comment by pan-zhuo** [comment]
> Finally, mapping of $3 (material specified) raises similar questions to what we discussed today, in that, if there are not RDA entities (with URIs) for the part(s) of the expression or manifestation referenced in $3, we can't hope to match up that statement to more information about that part. Since $3 text isn't controlled, that hope is a faint one anyway.
> 
> Options include,
> 
> 1. reifying the metadata "work" (triple) containing the $a statement and then adding a "note on metadata work" about the triple, or
> 2. appending the content of $3 to the end of the statement built from $a with some contextual punctuation.  Something like:
> 
> [Expression URI] http://rdaregistry.info/Elements/e/P20322 "Reading grade level: 3.1 (applies to: booklet)"
> 
> 2. would be a "lossy" method, but probably not too much of a loss.   I'm ok selecting this and documenting the necessary transformations for now, if we can label this "Loss" and review at the end.
> 
> Is this approach in line with other mappings we've done? @CECSpecialistI

$3 is tricky in the context of [Aggregates](https://access.rdatoolkit.org/Guidance/Index?externalId=en-US_ala-bd1f1ef9-978c-34ee-8881-acc1500130b9). If a book is issued together with a booklet, they are two manifestations each embodying an expression. If we choose to create a manifestation URI for the whole, there are three expressions manifested:

```
[AggregateManifestation] rdam:P30139 [AggregatingExpression] .
[AggregateManifestation] rdam:P30139 [Expression1] . # the expression realized in the book
[AggregateManifestation] rdam:P30139 [Expression2] . # the expression realized in the booklet
[AggregatingExpression] rdae:P20319 [Expression1] .
[AggregatingExpression] rdae:P20319 [Expression2] .
```

I don't think we can say this:
`[AggregatingExpression] rdae:P20322 "Reading grade level: 3.1 (applies to: booklet)" .`
It seems that we can't reify the statement and put the qualifying info in Work: note on metadata either, because 'an aggregating expression does not incorporate or accumulate the expressions that are aggregated.' (88.69.69.51)

I think we can only say: 
`[Expression2] rdae:P20322 "Reading grade level: 3.1" .`

But if there's another tag that describes the booklet, like:
`774 08 ǂi Container of (manifestation): [information about the booklet]`

Then we will need to create a manifestation URI for the booklet:
`[Manifestation2] rdam:P30020 [AggregateManifestation] . # the booklet is part of the whole`

It does seem hopeless that we will be able to link the booklet manifestation with the booklet expression.
A similar situation is when $3's appear in multiple tags.

An easier solution could be to use Manifestation: note on manifestation (73.81.62.04) or Expression: note on expression (39.16.08.94).

**Comment by lake44me** [comment]
@CECSpecialistI  Hmmm.  I don't see how we can create a note on expression to give details on another note on expression (which I'm choosing as the primary relation for 521 $a).  They need to be linked somehow and that would involve making note number 1 be the subject of a triple, wouldn't it?

@pan-zhuo Thanks for your comments.  About $b, I was going to just append it at the end of the string with prefix of "Source".  Because the definition is squishy (source agency or entity).   Entity?  But I'm coming around to "Assigned by".

**Comment by lake44me** [comment]
So I went ahead for now and have just done the unstructured mapping of everything into one prepended, appended string, labeled it "loss" and maybe we should add to the RSC questions for now?  Or does anyone have more suggestions?  
Again, I've mapped or deleted every row except for subfields 6 and 8.  Should I move this into Awaiting Review yet?  @CECSpecialistI you could always kick it back to "In Progress" :-)

**Comment by CECSpecialistI** [comment]
Thank you @lake44me , sorry for not being as responsive as I'd like to be on this discussion so far. The choices you've made here make perfect sense to me, and if you feel good about them too, leaving status "loss" or "?" on things you think need extra attention is totally fine to do as you move this to "Awaiting review".

**Comment by CECSpecialistI** [comment]
Continue asynchronous discussion [here](https://github.com/uwlib-cams/MARC2RDA/discussions/349). We will discuss at meeting on 2022-04-27.

**Comment by lake44me** [comment]
I have made the changes to provide different mappings to note on manifestation or note on expression based on the Ind. 1 display constant controller as we discussed.  Need to re-check the coverage on this (I think I am deleting a field that I added previously, but it may have been one of the original fields), and also see if there's a better way to insert an example mapped field in transformation notes (line 39, subfield 3 proposed mapping).   This is a general problem.  Awaiting decisions on subfields 6 and 8, otherwise it will be done.

**Comment by pennylenger** [comment]
Based on discussion above and[ here ](https://github.com/uwlib-cams/MARC2RDA/discussions/349),  I changed the mapping to has intended audience of expression if the first indicator is 0 (although I don't understand why  "0" “Reading grade level” indicates semantics that are entirely at expression level), and others to has note on manifestation.

**Comment by GordonDunsire** [comment]
@pennylenger: I understand the point of view of your question. As I said in the previous discussion on field 521, it seems to me that only indicator 1 = 0 is definitely and objectively an expression statement. Reading grade is based on the language of the content, which is an expression characteristic. The other first indicator values pertain to the subject of the content, which is a work characteristic. There is no work element for intended audience of the work; the concept only applies to a representative expression.

It also seems to me that reading grade is an objective measurement, in the context of readers of text in the place associated with the expression. This would be measured against national objectives for public education. The other values are more subjective and are sourced from sub-national groups with different contexts; some of the examples in the MARC 21 manual seem to be marketing recommendations.

So I think the safest default is to transform the data to a note on manifestation element, as recommended at the beginning of the discussion. I now think this should be done for reading grade as well as the other indicator values. An additional mapping to the expression element should be considered when the implications of aggregate detection are finally agreed on; the question, already mentioned in the discussion on field 521, is the choice of expression, expression aggregated, or aggregating work.
