### ISSUE TITLE
561 ownership and custodial history

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#225]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by lake44me** [comment]
This note is challenging because of the possible value "0" (Private) in ind. 1.  Otherwise, straightforward in that we can only map the main content subfield $a to "note on item" (and mint an IRI for item asssociated with the manifestation).

My thought is, since the "private" designation applies only to the note, the note needs to become a "metadata work" so we can say something about it.  
Would something like this work?  Other possibilities?   (this is a transformation note for $a mapping)
*Create a set of reified triples derived from this MARC tag.  Included in that set, 
mint item IRI and associate with manifestation (has exemplar of manifestation 
*  ex: manifestationIRI rdamo:p30103  ex:itemIRI
*  ex:itemIRI rdaid:p40028 "contents of subfield a"
*  Assign a (metadata) work IRI to this set of triples
*  (give it an appellation)
*  Associate the (metadata) work to the minted item IRI using property rdaio:P40164  item described with metadata by
*  Associate a (metadata) manifestation IRI to the work IRI using property rdawo:P10072  has manifestation of work  
*  (give the (metadata) manifestation an appellation 
* Associate a value to the manifestation using property http://rdaregistry.info/Elements/m/P30145  restriction on access to manifestation.   This could be unstructured string "Private",  or preferably a value taken from a value vocabulary if one can be found that conveys the meaning.
This is clunky - currently there is no property for a metadata work that indicates access restriction, but there's no direct path to a "metadata manifestation".

Wonder if this is the only tag with such an indication in an indicator or elsewhere about restrictions on letting people access it.  
@CECSpecialistI @GordonDunsire

**Comment by lake44me** [comment]
'Example of reified mapping of tag 561 if Ind1 = 0 (Private)

ex:Item1  rdaio:P40049  ex:Manifestation1  [has manifestation exemplified]
[... if subfield 5 is present, relate item to owning institution etc. per that mapping]  

ex:Item1 rdaio:P40164  ex:MetaWork1   [is item described with metadata by]

ex:MetaWork1 rdf:type  rdf:statement .
ex:MetaWork1 rdf:subject  ex:Item1
ex:MetaWork1 rdf:predicate  http://rdaregistry.info/Elements/i/P40026   [has custodial history of item] 
ex:MetaWork1 rdf:object  "[contents of 561 subfield a (literal]" .
ex:MetaWork1  
ex:MetaWork1 rdawo:P10078  ex:MetaManifestation1  [manifestation of work]  
ex:MetaManifestation1  rdamd:p30145 "Private" [restriction on access to manifestation]

ex:Item1 rdaio:P40164  ex:MetaWork2
ex:MetaWork2 rdf:type rdf:statement .
ex:MetaWork2 rdf:subject ex:Item1 .
ex:MetaWork2 rdf:predicate http://rdaregistry.info/Elements/i/P40026  .  
ex:MetaWork2 rdf:object "[contents of 561 subfield u (uri) as a literal]" .   //???  not sure if it can be the URI itself inside this reification
ex:MetaWork2 rdawo:P10078  ex:MetaManifestationw  [manifestation of work]  
ex:MetaManifestation1  rdamd:p30145 "Private" [restriction on access to manifestation]'

**Comment by lake44me** [comment]
Please review, suggest better ways if possible...  
Note that rdam: p30145  "restriction on access to manifestation" only accepts an unstructured description.
Could we use rdaw: p10004 "Category of work" and devise a category for a Metadata Work that designated its intended consumption?  or possibly some other Work property?
  
I'd rather there was a controlled value meaning "private" somewhere we could plug in but can't find one.

**Comment by GordonDunsire** [comment]
Please note that there is a proposal to be discussed by RSC later this month which will allow rdam:P30145 to accept a structured description/VES. The proposal is likely to be accepted, and be incorporated into RDA early in the new year.

**Comment by GordonDunsire** [comment]
However, rdam:P30145 is not the appropriate property to use. As the example shows, it is a manifestation property, but the 'private' restriction applies to the metadata work and all of its expressions and manifestations. I agree that rdaw:P10004 is better, and there is no need to mint the metadata manifestation. The values of 'category of metadata work' are, in this context, binary: private or public?

The status of private vs public is related to other statuses that an RDF graph (metadata work) might have, such as "deprecated". Note that the Open Metadata Registry has a [vocabulary of statuses](http://metadataregistry.org/concept/list/vocabulary_id/31.html) for VES concepts. The status of RDF graphs must be an issue for linked data communities ... but I can't immediately find an appropriate resolution.

**Comment by lake44me** [comment]
Thank you Gordon.  I'm glad you see 'Category of work" as the better option, and just use the term unstructured.  If we come across a VES that has a concept that comes close (private, not for publication, etc.) we could see whether we wanted to use it later.  I don't know if this is the same as a status.  I'd consider "not published" to be a status, but statuses can change.  This should be a value somewhere that a system could use to prevent something's status from ever becoming "published".

**Comment by lake44me** [comment]
'Revised example of reified mapping of tag 561 if Ind1 = 0 (Private)

ex:Item1  [mint item]  rdaio:P40049 ex:Manifestation1 [has manifestation exemplified]
[... if subfield 5 is present, relate item to owning institution etc. per that mapping]

ex:Item1 rdaio:P40164 ex:MetaWork1 [is item described with metadata by]
ex:MetaWork1 rdf:type rdf:statement .
ex:MetaWork1 rdf:subject ex:Item1
ex:MetaWork1 rdf:predicate http://rdaregistry.info/Elements/i/P40026 [has custodial history of item]
ex:MetaWork1 rdf:object "[contents of 561 $a a plus any addition from $3 (literal]"] .
ex:MetaWork1 rdawd:P10004 "private" [category of work]

ex:Item1 rdaio:P40164 ex:MetaWork2
ex:MetaWork2 rdf:type rdf:statement .
ex:MetaWork2 rdf:subject ex:Item1 .
ex:MetaWork2 rdf:predicate http://rdaregistry.info/Elements/i/P40026 .
ex:MetaWork2 rdf:object "[contents of 561 $u (uri) plus any addition from $3 as a literal]" . 
//note:  although $u is defined for 561,  rdai:P40026 permits only unstructured or structured literal strings.
ex:MetaWork1 rdawd:P10004 "private" [category of work]`

**Comment by pan-zhuo** [comment]
I wonder what is achieved by mapping $u separately, when RDA does not allow recording IRIs for [rdai:P40026](http://rdaregistry.info/Elements/i/P40026) "has custodial history of item". Seems to me that $a and $u can be joined using a boilerplate:

ex:Item1 rdaid:P40026 "[$a] (Additional information can be found at $u)"

$u is repeatable, so right now in the code I'm doing reification multiple times.

<< ex:Item1 rdaid:P40026 [$a] >> rdawd:P10004 "Private".   // Reified statement 1
<< ex:Item1 rdaid:P40026 "http://fakeIRI2.edu/fake1" >> rdawd:P10004 "Private".   // Reified statement 2
<< ex:Item1 rdaid:P40026 "http://fakeIRI2.edu/fake2" >> rdawd:P10004 "Private".   // Reified statement 3

I'd really like to cut down on the number of reifications needed. $u here is just a text string anyway.

**Comment by CECSpecialistI** [comment]
> 

I think @pan-zhuo is right; nothing seems to be gained from separate statements for a $u if that is just going to be a string. Reification to say something is private seems reasonable to me, though.

**Comment by gerontakos** [comment]
My opinion is that it doesn't matter much either way. I would consider that we conceived of this as a practice run, a demonstration of how to perform reification in RDA/RDF. So I would choose the demonstration that serves better as a demonstration, which I would say is "reification multiple times." But really I don't think it matters too much; either way, we make a good demonstration.

I'm confused about the use of rdawd:P10004; specifically, I'm most confused that a Work property would be used. How could the metadata WORK be private? Isn't the metadata Manifestation private? (Sometimes ubiquitous WEMIfication seems like a tremendous burden.) Then, on a related issue, I'm wondering how "private" can be considered a category for a Work. I don't see the public/private categorization is pertinent to works, so if the value "private" remains related to the metadata Work, wouldn't it make more sense as a mere note?

**Comment by pan-zhuo** [comment]
> How could the metadata WORK be private? Isn't the metadata Manifestation private?

This reminds me that the minimum description of a work must include a link to an expression or manifestation. Apparently, we are not interested in the metadata expression (unless we want to talk about the language used in the metadata description), then we will need to mint a metadata manifestation anyway, is that correct?

If so, what does that manifestation IRI look like? Suppose you have a metadata work IRI

http://fakeIRI2.edu/MetaWork1

Is the manifestation IRI

http://fakeIRI2.edu/MetaMan1

Or,

http://fakeIRI2.edu/MetaWork1.rdf
http://fakeIRI2.edu/MetaWork1.ttl
http://fakeIRI2.edu/MetaWork1.html

**Comment by GordonDunsire** [comment]
@gerontakos: We are talking specifically about a category of metadata work that is a single metadata statement.

We could say that there are two categorization schemes being applied:

1. Categories of work: static work; diachronic work; aggregating work; collection work (these are all explicit in RDA, but RSC has rightly decided not to offer guidance or vocabularies for "category" elements (one for each Entity).
2. Categories of metadata work: single statement; multiple statement; public; private; single entity; multiple entity (categories may be combined). A category of "private" would be defined something like "A metadata work that is intended for a closed information system".

@pan-zhuo: For metadata WEM IRIs, we can flip the process I suggested for MARC 21 WEMs:

There is no 'record control number' that can be used as a local part, so we use our own running number (e.g. 1).
Start with Work: exW/1
Add Expression: exW/1 rdamo:P10078 exE/1 .
Add minimal conformance condition for Works: exW/1 rdawd:P10002 stringify(exW/1) .
Add minimal conformance condition for Expressions: exE/1 rdaed:P20002 stringify(exE/1) .
Or: exE/1 rdaed:P20062 "rdf+xml" . // has form of notation

The manifestation of this metadata work is the file that the transform writes to, so we can't mint it ourselves. Note that the manifestation of a set of metadata works is an aggregate of expressions of the metadata works, so it embodies an aggregating work and expression. The aggregating work is the transform because it selects, etc. the metadata works to create, realize, and embody.

**Comment by AdamSchiff** [comment]
Some examples (I've included 1xx/2xx for context):

245 04 The new international dictionary of New Testament theology / ǂc Colin Brown, general editor.
505 00 ǂg v. 1. ǂt A-F -- ǂg v. 2. ǂt G-Pre -- ǂg v. 3. ǂt Pri-Z.

100 1 Marsalis, Ellis, ǂe composer, ǂe instrumentalist.
245 10 Heart of gold / ǂc Ellis Marsalis.
505 00 ǂt Have you met Miss Jones? (4:07) -- ǂt Never let me go (7:00) -- ǂt Chapter 2 (3:46) -- ǂt This can't be love (3:56) -- ǂt Spring can really hang you up the most (3:50) -- ǂt Swinging at the Haven (4:31) -- ǂt Heart of gold (3:43) -- ǂt Dr. Jazz (4:28) -- ǂt Do you know what it means to miss New Orleans (6:27) -- ǂt I can't give you anything but love (5:18) -- ǂt Surrey with the fringe on top (6:57) -- ǂt Love for sale (6:00) -- ǂt Sweet Georgia Brown (7:10) -- ǂt El-Ray blues (4:37) -- ǂt A nightingale sang in Berkeley Square (3:16).
[The durations are not encoded in $g]

100 1 Liu, Yan ǂc (Cultural historian), ǂe author.
245 10 Healing with poisons : ǂb potent medicines in medieval China / ǂc Yan Liu.
505 00 ǂt Pt. I Malleable Medicines -- ǂt ch. 1 The Paradox Of Dm -- ǂt ch. 2 Transforming Poisons -- ǂt pt. II Knowledge, Authority, and Practice -- ǂt ch. 3 Fighting Poison With Poison -- ǂt ch. 4 Medicines In Circulation -- ǂt ch. 5 Medicines In Practice -- ǂt pt. III Enhancing the Body -- ǂt ch. 6 Alluring Stimulant -- ǂt ch. 7 Dying To Live.

130 0 崖の上のポニョ(Motion picture)
130 0 Gake no ue no Ponyo (Motion picture)
245 10 Ponyo / ǂc Walt Disney Pictures ; Studio Ghibli, Nippon Television Network, Dentsu, Hakuhodo Dymp, Buena Vista Home Entertainment, Mitsubishi and Toho ; producer, Toshio Suzuki ; written and directed by Hayao Miyazaki ; U.S. production directors, John Lasseter, Brad Lewis, Peter Sohn ; executive producers, John Lasseter, Kathleen Kennedy, Frank Marshall ; English language screenplay, Melissa Mathison.
505 00 ǂg Disc 1: ǂt Feature film ; ǂt "Meet Ponyo" (introduction by the producers) -- ǂg Disc 2: ǂt Bonus (Original Japanese storyboards) ; ǂt "World of Ghibli" ("Behind the studio" (discover the film's inspiration through documentaries, including all-new interviews with Hayao Miyazaki)) ; ǂt "Enter the lands" (meet the characters and hear the story of the movie).

245 00 Biopsychosocial assessment in clinical health psychology / ǂc edited by Frank Andrasik, Jeffrey L. Goodie, Alan L. Peterson.
505 00 ǂt Part I. Overview -- ǂt ch. 1. Introduction to biopsychosocial assessment in clinical health psychology / ǂr Alan L. Peterson, Jeffrey L. Goodie, and Frank Andrasik -- ǂt ch. 2. Fundamentals of assessment in clinical health psychology / ǂr Cynthia D. Belar and William W. Deardorff -- ǂt ch. 3. Medication adherence / ǂr Howard Leventhal [and others] -- ǂt Part II. Assessment in health-risk behaviors -- ǂt ch. 4. Eating disorders / ǂr Susan Himes, Tovah Yanover, and J. Kevin Thompson -- ǂt ch. 5. Tobacco use / ǂr Alan L. Peterson, Antionette R. Brudige, and David Houghton -- ǂt ch. 6. Drug use and abuse / ǂr Deborah L. Haller [and others] -- ǂt ch. 7. Alcohol use / ǂr Tony Toneatto and Mekhala Gunaratne -- ǂt ch. 8. Social support / ǂr Merideth D. Smith and Amy Fiske -- ǂt ch. 9. Coping / ǂr Lauren M. Penwell-Waines, Kevin T. Larkin, and Jeffrey L. Goodie -- ǂt ch. 10. Physical activity / ǂr Patricia M. Dubbert, Todd A. Smitherman, and Jeanne Gabriele -- ǂt ch. 11. Quality of life / ǂr Jan Passchier and Jan Busschbach -- ǂt Part III. Assessment of clinical problems -- ǂt ch. 12. Cancer / ǂr Tammy A. Schuler, Thomas M. Atkinson, and Errol J. Philip -- ǂt ch. 13. Cardiovascular disease / ǂr Benson M. Hoffman, Ay Goetzinger, and James A. Blumenthal -- ǂt ch. 14. Chronic pain / ǂr Donald D. McGreary [and others] -- ǂt ch. 18. Gastrointestinal disorders / ǂr Branda B Toner and Iman Hussain -- ǂt ch. 19. Insomnia / ǂr Daniel J. Taylor [and others] -- ǂt Part IV. Assessment of special populations -- ǂt ch. 21. Cultural concerns / ǂr Luz Garcini [and others] -- ǂt ch. 22. Organ transplant / ǂr Douglas P. Gibson [and others] -- ǂt ch. 23. Bariatric surgery / ǂr Mary Ellen Olbrisch, Melanie K. Bean, and Karen E. Stewart -- ǂt ch. 24. Pediatrics / ǂr Lisa M. Buckloh and Lisa M. Schilling -- ǂt ch. 25. Older adults / ǂr Christine E. Gould, Merideth D. Smith, and Barry A. Edelstein -- ǂt ch. 26. Primary care / ǂr Christopher L. Hunter.

245 00 Experience-driven leader development : ǂb models, tools, best practices, and advice for on-the-job development / ǂc [edited by] Cynthia D. McCauley, D. Scott DeRue, Paul R. Yost, Sylvester Taylor.
505 00 ǂt Part I. Developmental experiences : more intentional for more people -- ǂt Section A. Equipping employees to pursue developmental experiences -- ǂt ch. 1. Intensity and stretch : the drivers of on-the-job development / ǂr Mark Kizilos -- ǂt ch. 2. A leadership experience framework / ǂr Paul Van Katwyk, Joy Hazucha, and Maynard Goff -- ǂt ch. 3. Identifying development-in-place opportunities / ǂr Cynthia McCauley -- ǂt ch. 4. Leadership maps : identifying developmental experiences in any organization / ǂr Paul Yost and Joy Hereford -- ǂt ch. 5. Building organization-specific knowledge about key developmental experiences / ǂr Paul R. Bly and Mark Kizilos -- ǂt ch. 6. Expression of interest : making sought-after roles visible / ǂr Tanya Boyd -- ǂt ch. 7. Designing part-time cross-functional experiences / ǂr Nisha Advani -- ǂt ch. 8. Creating project marketplaces / ǂr Cynthia McCauley -- ǂt Section B. Leveraging existing experiences for learning -- ǂt ch. 9. Leveraging the developmental power of core organizational work / ǂr Patricia M.G. O'Connor -- ǂt ch. 10. Learning transferable skills through event planning / ǂr Kenna Cottrill and Kim Hayashi -- ǂt ch. 11. Pinpointing : matching job assignments to employees / ǂr Jeffrey J. McHenry -- ǂt ch. 12. Learning from personal life experiences / ǂr Marian N. Ruderman and Patricia J. Ohlott -- ǂt Section C. Creating new developmental experience -- ǂt ch. 13. Strategic corporate assignments to develop emerging market leaders / ǂr Anita Bhasin, Lori Homer, and Eric Rait -- ǂt ch. 14. Full-time strategic projects for high potentials / ǂr Paul Orleman -- ǂt ch. 15. A personalized rotation program to develop future leaders / ǂr Bela Tisoczki and Laurie Bevier -- ǂt ch. 16. Corporate volunteerism as an avenue for leader development / ǂr Shannon M. Wallis and Jeffrey J. McHenry -- ǂt ch. 17. Developing socially responsible global leaders through service projects / ǂr Mathian Osicki and Caroline Smee -- ǂt ch. 18. Stretch assignments to develop first-time supervisors / ǂr Sally A. Allison and Marsha Green -- ǂt ch. 19. Executive shadowing / ǂr Ritesh Daryani -- ǂt ch. 20. Leadership fitness challenge : daily exercise of the leadership muscle / ǂr Laura Ann Preston-Dayne -- ǂt ch. 21. Using a video-case-based collaborative approach in leader development / ǂr Nate Allen -- ǂt ch. 22. Cross-company consortiums : tackling business challenges and developing leaders together / ǂr Yury Boshyk -- ǂt Part II. Leaders : better equipped to learn from experience -- ǂt Section D. Organizing frameworks -- ǂt ch. 23. Mindful engagement : learning to learn form experience / ǂr D. Scott DeRue and Susan J. Ashford -- ǂt ch. 24. PARR : a learning model for managers / ǂr Laura Ann Preston-Dayne -- ǂt ch. 25. GPS-R : a tool for assessing learning readiness / ǂr Paul Yost, Hillary Roche, and Jillian McLellan -- ǂt Section E. Learning strategies and tactics -- ǂt ch. 26. Asking questions to foster learning from experience / ǂr Sally Beddor Nowak -- ǂt ch. 27. Using the classroom to create a learning orientation / ǂr Lori Homer and Anita Bhasin -- ǂt ch. 28. Establishing a learning mindset / ǂr Kelly A. Bunker -- ǂt ch. 29. Tactics for learning from experience / ǂr Maxine Dalton -- ǂt ch. 30. Narrating emotions to enhance learning / ǂr Shirli Kopelman and Ilan Gewurz -- ǂt ch. 31. Proactive feedback seeking : the power of seeing yourself as others see you / ǂr Susan J. Ashford -- ǂt ch. 32. Feedback : who, when, and how to ask / ǂr Sylvester Taylor -- ǂt ch. 33. Micro-feedback : a tool for real-time learning / ǂr Tanya Boyd -- ǂt Section F. Reflection and retention -- ǂt ch. 34. Leadership journeys : intentional reflection experiences / ǂr Nicole L. Dubbs [and others] -- ǂt ch. 35. After-event reviews : how to structure reflection conversations / ǂr D. Scott DeRue -- ǂt ch. 36. Scaffolding reflection : what, so what, now what? / ǂr Claudia Hill -- ǂt ch. 37. Life journeys : developing for the future by looking at the past / ǂr Kerry A. Bunker -- ǂt ch. 38. Strategies for facilitating learning from experience / ǂr Claudia Hill -- ǂt ch. 39. Teachable point of view : learning to lead by teaching others / ǂr Scott McGhee -- ǂt ch. 40. Implementation intention : a refinement to leadership development goal setting / ǂr Luke Novelli, Jr. -- ǂt ch. 41. Twelve questions for more strategic work and learning / ǂr Kelly McGill -- ǂt Section G. Learning communities and support -- ǂt ch. 42. Building a board of learning advisors / ǂr Marisa Bossen and Paul Yost -- ǂt ch. 43. Building a learning community through reflection and experimentation / ǂr Jennifer Jaramillo and Kristen Schultz -- ǂt ch. 44. Using communities of practice to cultivate leaders of integrity / ǂr John R. Terrill -- ǂt ch. 45. CompanyCommand : a peer-to-peer learning forum / ǂr Nate Allen -- ǂt ch. 46. Virtual roundtables : using technology to build learning communities / ǂr Jonathan Winter.
505 00 ǂt Part III. Human resource systems : designed for experience-driven development -- ǂt ch. 47. Integrated talent management and experience-based development / ǂr Norm Tonina -- ǂt Section H. Selection and on-boarding -- ǂt ch. 48. Identifying and assessing for learning ability / ǂr Paul Yost and Jillian McLellan -- ǂt ch. 49. On-the-job development that starts on day one / ǂr Drad Borland -- ǂt ch. 50. New leader assimilation / ǂr Tanya Boyd -- ǂt ch. 51. Virtual on-boarding / ǂr Ritesh Daryani -- ǂt Section I. Managers as developers -- ǂt ch. 52. Leaders coaching leaders : cascading leadership development through the organization / ǂr Robert J. Thomas, Claudy Jules, and Joshua Bellin -- ǂt ch. 53. An exercise for manager : developing talent through assignments / ǂr Cynthia McCauley -- ǂt ch. 54. Performance and development through conversation / ǂr Jonathan Winter -- ǂt Section J. Performance management -- ǂt ch. 55. Performance management and leadership development : paradox or potential? / ǂr Robert McKenna and Robleh Kirce -- ǂt ch 56. Performance management catalysts for experience-driven development / ǂr Paul Yost -- ǂt Section K. Training, development, and beyond -- ǂt ch . 57. Training and experience-driven development / ǂr Paul Yost -- ǂt ch. 58. Bringing the real work into the classroom / ǂr Elaine Biech -- ǂt ch. 59. Cultivating learning agility : lessons from the microfinance sector / ǂr Lyndon Rego, Vandana Viswanathan, and Peg Ross -- ǂt ch. 60. HoTspots (HubsoTraining) : a blended group learning solution to extend traditional training / ǂr Eric Berg -- ǂt ch. 61. Building experience into simulations / ǂr James Chisholm, Greg Warman, and Andrew Webster -- ǂt ch. 62. Mentoring : building leaders in powerful developmental relationships / ǂr Dana Kendall -- ǂt Section L. Action Learning -- ǂt ch. 63. Business driven action learning / ǂr Yury Boshyk -- ǂt ch. 64. Action learning with community-based nonprofits / ǂr Lynn Fick-Cooper and Shera Clark -- ǂt ch. 65. Better together : building learning communities across organizations / ǂr Jan Wilmott -- ǂt ch. 66. Communities of practice : building and sustaining global learning communities / ǂr Yury Boshyk -- ǂt Section M. Succession management -- ǂt ch. 67. Succession planning : developing general managers through experience / ǂr Mary M. Plunkett -- ǂt ch. 68. Building breadth and depth through experience / ǂr Jennifer Kennedy Marchi -- ǂt ch. 69. Profiles for success : building a framework for internal transitions / ǂr Tanya Boyd -- ǂt ch. 70. Hot jobs, hot people : sharing leadership talent across organizations / ǂr Jeffrey J. McHenry -- ǂt ch. 71. Multicultural women in the pipeline : finding hidden treasure / ǂr Ella L.J. Edmondson Bell -- ǂt Part IV. The organization : enabler of experience-driven development -- ǂt Section N. Frameworks for assessing organizations -- ǂt ch. 72. Organizational climate for development / ǂr Cynthia McCauley -- ǂt ch. 73. Creating the "and" organization : seeing leadership development as a key strategic issue / ǂr Stephen R. Mercer -- ǂt Section O. Designing tools for widespread use -- ǂt ch. 74. Leading from where you are / ǂr Paul Yost and Emily Pelosi -- ǂt ch. 75. My needs, their needs : designing high-value development tools / ǂr Rob McKenna, Mary M. Plunkett, and Kayode Adeuja -- ǂt ch. 76. Built to last : sustainable on-the-job development interventions for the entire organization / ǂr Paul Yost and Emily Pelosi -- ǂt Section P. Influencing organizational leaders -- ǂt ch. 77. Building support for experience-based development / ǂr Brad Borland -- ǂt ch. 78. The power of stories in leadership development / ǂr Paul Yost and JIllian McLellan -- ǂt ch. 79. Assessing learning's impact on careers / ǂr Richard A. Guzzo and Haif R. Nalbantian -- ǂt ch. 80. Teaching senior leaders the dynamics of derailment / ǂr Cynthia McCauley and Sylvester Taylor -- ǂt Section Q. Solutions to specific obstacles -- ǂt ch. 81. Strengthening executive mobility / ǂr Nora Gardner and Cameron Kennedy -- ǂt ch. 82. Talent ecosystems : building talent through strategic partnerships / ǂr D. Scott DeRue.

100 1 Schumann, Robert, ǂd 1810-1856, ǂe composer.
240 10 Symphonies
245 10 Symphonien 1-4 / ǂc Robert Schumann.
246 1 Simon Rattle conducts Schumann's symphonies
505 00 ǂg CD 1. ǂt Symphony no. 1 "Frühlingssymphonie" (31:07) ; ǂt Symphony no. 4, 1841 version (24:57) -- ǂg CD 2. ǂt Symphony no. 2 (38:04) ; ǂt Symphony no. 3 "Rheinische" (30:38).
505 00 ǂg Blu-ray video. ǂt Symphony no. 1 "Frühlingssymphonie" -- ǂt Symphony no. 4, 1841 version -- ǂt Symphony no. 2. -- ǂt Symphony no. 3 "Rheinische" -- ǂt Bonus: Sir Simon Rattle in conversion -- ǂt Behind the scenes of the recording -- ǂt About the Berliner Philharmoniker's digital concert hall.
505 00 ǂg Blu-ray audio. ǂt Symphony no. 1 "Frühlingssymphonie" -- ǂt Symphony no. 4, 1841 version -- ǂg CD 2. ǂt Symphony no. 2 -- ǂt Symphony no. 3 "Rheinische."

100 1 Copland, Aaron, ǂd 1900-1990, ǂe composer, ǂe arranger of music.
240 10 Orchestral music. ǂk Selections
245 10 Orchestral works. ǂn 3, ǂp Symphonies / ǂc Copland.
505 00 ǂt An outdoor overture (1938) for orchestra ǂg (8:35) -- ǂt Symphony no. 1 (1926-28) for large orchestra / ǂr arrangement by the composer of the Symphony for organ and orchestra (1924) ǂg (22:40) -- ǂt Statements (1932-35) ǂg (19:25) -- ǂt Dance symphony (1929) for large symphony / ǂr arrangement by the composer of music from unstaged ballet Grohg (1922-25) ǂg (17:00)

245 00 UW symphony orchestra, November 6, 2015 : ǂb with guest artist Maria Larionoff, violin.
505 00 ǂt Two humoresques, for violin and orchestra, op. 87 / ǂr Jean Sibelius ǂr (Maria Larionoff, violin) ǂg (6:44) -- ǂt Violin concerto in D major / ǂr Igor Stravinsky ǂr (Maria Larionoff, violin) ǂg (23:06) -- ǂt Symphony no. 3, in E-flat major, op. 55, Eroica / ǂr Ludwig van Beethoven.

130 0 Wyatt Earp (Motion picture)
245 10 Wyatt Earp / ǂc Warner Bros. presents a Tig Productions/Kasdan Pictures production, a Lawrence Kasdan film ; executive producers, Jon Slan, Dan Gordon, Charles Okun, Michael Grillo ; written by Dan Gordon and Lawrence Kasdan ; produced by Jim Wilson, Kevin Costner, Lawrence Kasdan ; directed by Lawrence Kasdan.
505 00 ǂg Disc 1. Feature film: ǂt Tombstone prologue -- "Where you headed, Wyatt?" -- Homecoming -- "Blood counts the most." -- Blood in the street -- "The Earps always know." -- Outracing highwaymen -- Prizefight -- Bas business with Ed Ross -- A gun in his hand -- Urilla -- Typhoid -- Burning out the past -- Arkansas horse thief -- " ... what's left of you." -- Fugitive rider -- The Mastersons -- James' arrangement -- "How'd you like a job?" -- Morgan arrives -- "You're the man I'm looking for." -- New laws in Dodge City -- "You're not a deliberate man." -- Mattie -- Fort Griffin -- "Call me Doc." -- "Bat, I'm shot." -- "It all ends now!" ǂg (89 min.).
505 00 ǂg Disc 2. Feature film: ǂt Doc and Big Nose Kate -- Rampaging cowboys -- The Earp wives -- "It isn't easy being my friend." -- "It does sound quiet." -- "Wives come and go." -- Contempt of court -- "You're headed for war." -- Josie -- Fool with a photograph -- Brave lawman's death -- "You're afraid to say my name." -- "Empty yellow talk." -- Between two women -- "Only what we do." -- "Get out your gun and commence." -- October 26, 1881 -- "Let;s go." -- Walk to the O.K. Corral -- The gunfight -- "One big happy family." -- Safety of the Earps -- The verdict -- "They got me, Wyatt." -- "Kill 'em all." -- "What do you care?" -- "That's one for Morgan." -- "A marshal and an outlaw." -- "I'll be your family." -- Indian Charlie -- Good friends -- Canyon shootout -- Tommy Behind-the-Deuce -- "It happened that way." -- End credits ǂg (101 min.); Special features: It happened that way (14 min.); Wyatt Earp: Walk with a legend (23 min.); Lifted scenes (18 min.); Theatrical trailer (4 min.).
[There are some VERY long "titles" in one $t]


Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________
