### ISSUE TITLE
585 exhibitions note

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#236]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/5XX.csv

**Comment by lake44me** [comment]
I think I am done with this, but my choice for a 585 ("Copy-specific field that contains a note which cites exhibitions where the material described has been shown.") with no $5 indicating a specific item owner --- mapping $a to Note on manifestation instead of minting a phantom item to which to attach the note, and appending "Item exhibited" to the front of the note, may be open to question.   I am mindful that this note could appear in records for single ("manuscript") item manifestation descriptions, "special" copy descriptions, or other contexts where multiple copies of a manifestation exist but one was first exhibited as described in the note.  Without a $5 it is difficult to identify an item so I thought it not worth minting one. 
Our Theology library special collections cataloger makes use of this field - with the $5.
