### ISSUE TITLE
655 index term--genre/form

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#250]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/6XX.csv

**Comment by cspayne** [comment]
@pennylenger @GordonDunsire 
Is there a reason that $b and $c are not mapped for 655?

**Comment by GordonDunsire** [comment]
@cspayne: I think subfield $b can be mapped into the heading along with $a, $v, $x, $y, and $z (in order of appearance). Subfield $b seems to precede $a and acts as an adjectival qualifier for the form/genre in subfield $a, so there is no added punctuation (just a space between values).

I assume that the intention is to index under subfield $a, followed by the subfield $b qualifiers, because the MARC 21 manual talks about focus and non-focus terms, so it doesn't seem logical to not follow the same order in the heading, but the examples clearly show the reverse: 'Laminated marblewood bust' is coded in that order, not as 'Bust, laminated marblewood', which is what I expect from an index heading. That's partly why I left it out of the subject headings discussion document. I don't think the transform should 'fix' the encoding order.

Subfield $c is a facet indicator from the scheme of the heading terms. We don't know what the values mean without checking each scheme and developing a distinct transform for each, so my advice is to ignore the subfield.

All of this pertains to indicator 1 = 0 (Faceted). The field history says that field 755 (physical characteristic) was merged into field 655 around 1993. I guess that field 755 originally pertained to manifestation, but the distinction has been lost and our default is to category of work.
