### ISSUE TITLE
Consistent/Repeated Subfield Appendix

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#326]
Make a bucket for repeated subfields that are always the same, incl. appendix A, $3, etc. and link from all spreadsheets so we don't have to repeat ourselves

**Comment by pan-zhuo** [comment]
I was looking at 043 and run into the reappearing $2 issue. I thought it should qualify as a repeated subfield so I post things here.

$2 MARC code for the source of vocabulary. I think in most cases the value in $2 is mapped to an identifier for a vocabulary encoding scheme (VES). I see 3 options in RDA.

1. Specify the VES in an application profile. (39.13.99.59)

2. If the value in $a, $b etc. is an appellation of some entity, which often seems to be an entity related to the manifestation being described, record the value in $2 as [Nomen: scheme of nomen](http://www.rdaregistry.info/Elements/n/#P80069). In Turtle it might look like this:
```
<Manifestation> rdaproperty1 <Entity> .
<Entity> rdaproperty:hasAppellation <Nomen> .
<Nomen> rdan:P80068 '[value in $a, $b etc.]' ;
        rdan:P80069 '[value in $2]' .
```

3. If the value in $a, $b etc. is not an appellation of some entity, like a concept term, then it seems to meet the condition 'a source of metadata is not a manifestation that is being described' (72.25.24.71), and the option is to record the value in $2 as [Work: source consulted](http://www.rdaregistry.info/Elements/w/#P10406). In order to record data provenance, the metadata is treated as a Work. I'm not sure if this means [reification](https://www.w3.org/TR/rdf11-mt/#reification) in an RDF implementation. I'd imagine something like this in Turtle:
```
<Entity> rdaproperty1 '[value in $a, $b etc.]' .
<triple> a rdf:Statement;
         rdf:subject <Entity> ;
         rdf:predicate rdaproperty1 ;
         rdf:object '[value in $a, $b etc.]' ;
         rdaw:P10406 '[value in $2]' .
```

**Comment by AdamSchiff** [comment]
$2 may exist in the format, but I have never ever seen it used.  I doubt there are more than a handful, if any, in our catalog or in OCLC.  However, I guess we still need to map it.

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
Box 352900
Seattle, WA 98195-2900
aschiff @ uw.edu
________________________________

**Comment by CECSpecialistI** [comment]
I think $2 does belong in this appendix. I'm hoping we can map it consistently across MARC fields
