### ISSUE TITLE
RDA/LRM/RDF data produced for the MARC2RDA project

### ISSUE THREAD

**Issue by gerontakos** [uwlib-cams/MARC2RDA#390]
Hello all, a dataset has been produced for the group to review. It is in github at MARC2RDA/Working Documents/transformationCode/outputDataForReview. There is the input MARC dataset, from which an RDF dataset was derived and saved in two versions, one without labels and another with labels. The one with labels is probably easier to review; that's dataset-1-withLabels.rdf. You can review it before the upcoming meeting or we can review it together at our Wednesday morning meeting on April 26. Please remember only a few fields have been sent to output. We thought it might be good to review some data before we code more fields, make sure we're on the right track.

**Comment by pan-zhuo** [comment]
Source MARC data is now placed alongside corresponding RDA data. You can search for 'Fxxx' ('xxx' for MARC field tags, F245, F500, etc.) to get to the part you'd like to review. An index to the fields represented in the 2 datasets:

F020
F043
F245
F264
F306
F336
F337
F338
F340
F380
F382
F490
F500
F502
F504
F561
F880

<img width="518" alt="image" src="https://user-images.githubusercontent.com/100716525/233918431-df95d822-14ee-4f7f-ad57-9ac59af06133.png">
Example: searching for 'F336' content type

**Comment by GordonDunsire** [comment]
Here are my comments on Dataset 2:

1. <fake:marcfield>F245 10 $a Concertino per tromba e orchestra (2015) = $b für Trompete und Orchester = for trumpet and orchestra / $c Krzysztof Penderecki.</fake:marcfield>
<rdamd:P30134>für Trompete und Orchester = for trumpet and orchestra</rdamd:P30134>

Is this correctly encoded in MARC? The non-repeat of "Concertino" is a problem.

2. <fake:marcfield>F264 #1 $a Mainz : $b Schott, $c [2017]</fake:marcfield>
<rdamd:P30011>[2017]</rdamd:P30011>

I think we should strip off the brackets. They indicate that the data was taken from outside of the manifestation being described, which is provenance that is no longer relevant to retain.

3. <fake:marcfield>F264 #4 $c ©2017</fake:marcfield>
<rdamd:P30280>©2017</rdamd:P30280>

I think 264 2nd ind = 4 should transform to rdamd:P30007 "has copyright date". The copyright symbol, the phonogram symbol, the string "(c)", the string "(p)", the string "copyright", the string "phonogram copyright", the letter "c", or the letter "p" should be stripped from the value:
<rdamd:P30007>2017</rdamd:P30007>

4. <rdaed:P20215>For trumpet; piano [includes percussion staff]. Total performers: 2.</rdaed:P20215>

I think parentheses should be used in place of brackets. Brackets have a specific, albeit legacy, meaning and we should avoid potential confusion if we can.

5. <fake:marcfield>F264 #2 $a [Milwaukee, Wisconsin] : $b distributed in North and South America exclusively by Hal Leonard.</fake:marcfield>

<rdamd:P30108>[Milwaukee, Wisconsin] : distributed in North and South America exclusively by Hal Leonard.</rdamd:P30108>
<rdamd:P30085>[Milwaukee, Wisconsin]</rdamd:P30085>
<rdamd:P30173>distributed in North and South America exclusively by Hal Leonard.</rdamd:P30173>

Remove the brackets around dates and places in timespan and place elements, but retain in "statement" elements:

<rdamd:P30108>[Milwaukee, Wisconsin] : distributed in North and South America exclusively by Hal Leonard.</rdamd:P30108> // this is ok
<rdamd:P30085>Milwaukee, Wisconsin</rdamd:P30085>

6. <fake:marcfield>F490 1# $a Trumpet library = $a Trompeten-Bibliothek ; $v TR 30</fake:marcfield>
<rdamd:P30106>Trumpet library</rdamd:P30106>
<rdamd:P30106>Trompeten-Bibliothek ; TR 30</rdamd:P30106>

There should be a standard "statement" transform for the whole MARC 490 field, to produce:
<rdamd:P30106>Trumpet library = Trompeten-Bibliothek TR 30</rdamd:P30106>

I think we should remove the contents of subfields l (LC call number), y (invalid ISSN), and z (cancelled ISSN) [treat $3, $7 as per general decision ...]. Retain the punctuation; remove the subfield encoding.

7. <fake:marcfield>F500 ## $a This library lacks distributor information. $5 WaU</fake:marcfield>

This note is odd? A general note says the distributor info is taken from a label (presumably affixed by the seller) on the back cover, so does this note really say the WaU copy lacks the book jacket?

8. <fake:marcfield>F245 10 $a Onlinedating.teenadultdating/Adult-dating / $c Angela Genusa.</fake:marcfield>
<rdawd:P10088>OnlinedatingteenadultdatingAdult-dating</rdawd:P10088>

I think the embedded punctuation should not be stripped out:
<rdawd:P10088>Onlinedating.teenadultdating/Adult-dating</rdawd:P10088>

[Anomalous anyway, because the hyphen is left in.] Cf "has title of manifestation", which does not strip out the punctuation.

9. <fake:marcfield>F264 #1 $a [Place of publication not identified] : $b [Angela Genusa], $c 2012.</fake:marcfield>
<rdamd:P30111>[Place of publication not identified] : [Angela Genusa], 2012.</rdamd:P30111>
<rdamd:P30088>[Place of publication not identified]</rdamd:P30088>
<rdamd:P30176>[Angela Genusa]</rdamd:P30176>

The standard "statement" output is fine.

The standard value "[Place of publication not identified]" does not map to rdamd:P30088 = has place of publication. It should only be mapped into the statement output. The same applies to other standard "not identified" values.

Strip the brackets from name of publisher:
<rdamd:P30176>Angela Genusa</rdamd:P30176>

10. <fake:marcfield>F500 ## $a UW Libraries has an unbound copy of single leaves, starting with the title page and ending at page 121. $5 WaU</fake:marcfield>

Another strange "holdings" note. If the manifestation being described as "volume" as a carrier type, the UW note is referring to a separate manifestation, presumably a photo-reproduction or print-off, that is unbound and possibly incomplete. The transform is ok.

**Comment by briesenberg07** [comment]
***[GitHub Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) information***  
To use the `#` or `@` character without inserting a link to an issue or user, respectively, these can be escaped with a preceding backslash (`\`). Enclosing in backticks (\`\`) as I've done here works too.

**Comment by CECSpecialistI** [comment]
2023-05-03 discussed until #7 in Gordon's comment
