### ISSUE TITLE
030 coden designation

### ISSUE THREAD

**Issue by CECSpecialistI** [uwlib-cams/MARC2RDA#64]
https://github.com/uwlib-cams/MARC2RDA/blob/main/Working%20Documents/0XX.csv

**Comment by pan-zhuo** [comment]
$y in the linking entry fields is taken from 030 so I post my question here.

The [MARC manual](https://www.loc.gov/marc/bibliographic/bd030.html) says CODEN numbers are for periodicals, so I wonder if they are work identifiers like the ISSN.

But it seems that they are also assigned to [non-serial publications](https://www.cas.org/services/coden).

Toolkit maps them to manifestation and Bibframe maps to bf:Instance.

**Comment by GordonDunsire** [comment]
The [Wikipedia article on Coden[](https://en.wikipedia.org/wiki/CODEN) says "In contrast to a periodical CODEN, the first two characters of a CODEN assigned to a non-serial publication (e.g. conference proceedings) are [digits](https://en.wikipedia.org/wiki/Arabic_numeral)".

A serial CODEN should be treated the same as an ISSN; it is a Work identifier because of the WEM lock on serials (only one Manifestation and Expression, so any identifier identifies W, E, or M and we can associate it with Work because it is the best fit to LRM.

A non-serial CODEN should be treated as a Manifestation identifier (unless further research shows the same non-serial CODEN being applied to, say, the print and microform manifestations of the same work/expression.

It is trivial to differentiate between serial and non-serial CODENs.

Is there some kind of mapping/consolidation between ISSNs and serial CODENs anywhere? I can ask a colleague at the ISSN International Centre.

**Comment by pan-zhuo** [comment]
Thank you for your input @GordonDunsire. If we don't differentiate between serial and non-serial CODENs, then it's not wrong to map to manifestation identifiers in all cases, am I correct?

**Comment by GordonDunsire** [comment]
@pan-zhuo: I think it would be wrong for serial CODENs. If a serial CODEN maps to an ISSN, then it is a work identifier, not a manifestation identifier. Technically, a diachronic work identifier can also be used to identify its diachronic expression and manifestation because of the 1-1-1 cardinality (WEM lock), but I do not think this is safe, and the ISSN Network agrees. I think we have to differentiate the CODEN, but it is easy to do by machine.
